### ISSUE TITLE
Admin config form is not showing up

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/video_embed_field#1]
`The admin/config/media/vef_video_styles` is not currently working. 
This form is needed to add video styles or change existing styles.

Here are some screenshots from the Drupal 7 version;
![vef-config1](https://user-images.githubusercontent.com/871421/131555561-6777bb9e-3d22-4b54-8db0-b35d9306409b.png)

![Screenshot 2021-08-31 at 13-18-33 Edit video style normal Drupal7](https://user-images.githubusercontent.com/871421/131555606-a502ae34-5a43-45ab-8c2a-e99588e42d18.png)

And an export file: 
```
$video_embed_style = new stdClass();
$video_embed_style->disabled = FALSE; /* Edit this to true to make a default video_embed_style disabled initially */
$video_embed_style->api_version = 1;
$video_embed_style->name = 'normal';
$video_embed_style->title = 'Normal';
$video_embed_style->data = array(
  'vimeo' => array(
    'autoplay' => 0,
    'byline' => 1,
    'class' => '',
    'color' => '00adef',
    'froogaloop' => 0,
    'height' => 360,
    'loop' => 0,
    'portrait' => 1,
    'title' => 1,
    'width' => 640,
  ),
  'youtube' => array(
    'autohide' => 2,
    'autoplay' => 0,
    'class' => '',
    'controls' => 1,
    'height' => 360,
    'iv_load_policy' => 1,
    'modestbranding' => 0,
    'rel' => 0,
    'showinfo' => 1,
    'theme' => 'dark',
    'vq' => 'large',
    'width' => 640,
  ),
);
```

**Comment by sutibun** [comment]
Does this mean the Video Embed Field module doesn't work and I shouldn't install it on my Backdrop CMS? Or, does it work just fine even without this config form?

PS: It's like you know the good modules to port

**Comment by serundeputy** [comment]
hi @sutibun it works,  with the default provided video styles, but to make your own styles the form will need to work. 

i would say install it and see if it meets your needs with the defaults. 

thanks, 
Geoff

**Comment by sutibun** [comment]
@serundeputy Sweet. It works! I had misunderstood this issue.

This will do for now. Grazie!

**Comment by laryn** [comment]
Took a look at this and did not solve it but it seems related to CTools plugins. @herbdool recently added some guidance on converting CTools plugins to the wiki here:

https://github.com/backdrop-contrib/ctools/wiki/Converting-CTools-plugins

**Comment by herbdool** [comment]
That wiki might help but this might be a special beast as well. It's CTools Export UI in particular so might require more workarounds.

**Comment by laryn** [comment]
Perhaps rather than wrestling CTools we can rebuild this following the model of Flexslider optionsets:

> ![Screen Shot 2020-10-19 at 4 34 12 PM](https://user-images.githubusercontent.com/871421/96514260-031b1e00-1229-11eb-8a55-0d34e16a7557.jpg)

> ![Screen Shot 2020-10-19 at 4 34 22 PM](https://user-images.githubusercontent.com/871421/96514272-07dfd200-1229-11eb-8810-cb26acd8911c.jpg)

**Comment by laryn** [comment]
Another potential (which I haven't explored too deeply but posting here as something to consider) is rebuilding this configuration page with @BWPanda's [Preset API module](https://github.com/backdrop-contrib/preset).

> If your module needs a UI for adding, editing and deleting configuration presets, Preset API will do the heavy lifting for you.

**Comment by ghost** [comment]
Yes, Preset API seems to be a good candidate here. This sort of situation is more or less why I built it in the first place. Here's a lightning talk about Preset API if that helps: https://youtu.be/sE7Z4QE7zN0

**Comment by jenlampton** [comment]
Wow, Preset API module looks fantastic! I was thinking about building a replacement for the ctools exportables UI, but of course @BWPanda had that good idea long before I did :) Thank you!

**Comment by jenlampton** [comment]
I've pushed up a PR that provides the default 'Normal' video style, so that this module can work out of the box. 

I've also added integration with Preset API, so that if you want to have additional Video styles, adding that module will enable you to do so. I have not made that module a hard dependency for Video Embed field. 

Please note: the current integration with Preset API will require this PR to get merged: https://github.com/backdrop-contrib/preset/issues/6 (or for those who want to use this now apply this patch: https://github.com/backdrop-contrib/preset/pull/7.patch)

**Comment by laryn** [comment]
This is great! I'll wait to see how things unfold in Preset first and look forward to getting things working here.

**Comment by laryn** [comment]
I'm not sure how quickly the Preset piece will move forward, but I think I'll merge this for now since Preset isn't a hard requirement. If things change over there we may need to modify things here as well.
