### ISSUE TITLE
Add laryn as maintainer

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/video_embed_field#17]
I see you are looking for maintainers @serundeputy -- I use this on a few sites and am willing to be a co-maintainer if that sounds okay to you.

**Comment by serundeputy** [comment]
Sounds great! Is there something I have to do to make you a maintainer?

Last time I was in backdrop world all contributors had commit access.

**Comment by laryn** [comment]
@serundeputy Yes, I think permissions have tightened up some since then. If you merge the PR adding me to the README and add me as an admin under the repo's **Settings > Manage access** it should be enough.

**Comment by serundeputy** [comment]
nice! i've added `write` access to @laryn , but i don't see any PR adding you to the readme.md

**Comment by laryn** [comment]
@serundeputy Oops I made the commit on my fork but didn't PR it. :flushed: 
https://github.com/backdrop-contrib/video_embed_field/pull/18

**Comment by serundeputy** [comment]
lgtm; merge away!

**Comment by laryn** [comment]
Thanks!
