### ISSUE TITLE
Invalid argument foreach loop

### ISSUE THREAD

**Issue by serundeputy** [backdrop-contrib/video_embed_field#2]
this is related to styles issue (which used ctools); so it maybe that if we solve #1 we will solve this too.

<img width="855" alt="screen shot 2015-08-30 at 6 59 14 pm" src="https://cloud.githubusercontent.com/assets/6763671/9570120/6ee29ecc-4f4e-11e5-8d22-5c281f3d4abb.png">

```
Warning: Invalid argument supplied for foreach() in video_embed_field_video_style_options() (line 322 of /Users/geoff/Sites/serundrop/modules/contrib/video_embed_field/video_embed_field.module
```

**Comment by jackaponte** [comment]
Seeing this on a site of mine too; @serundeputy; doesn't block my use case but I might try to debug this or #1 in the future!

**Comment by laryn** [comment]
@serundeputy @jackaponte 

I added a fix for this in the PR on this one: https://github.com/backdrop-contrib/video_embed_field/issues/5

**Comment by serundeputy** [comment]
Thanks @laryn this is great!
merged;
care to co-maintain?

**Comment by laryn** [comment]
> care to co-maintain?

@serundeputy If you'd like, sure. I guess the last big thing before a release is the admin/config page.
