### ISSUE TITLE
Configuration page title isn't correct

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/video_embed_field#23]
The configuration page title of the module is "Settings". See below in context with some other configuration items. The page name should be "Video Embed Field" instead. (Maybe, the description could  also be adapted then.)

> Colorbox
> Adjust Colorbox settings.
>
> File system
> Tell Backdrop where to store uploaded files and how they are accessed.
>
> Image styles
> Configure styles that can be used for resizing or adjusting images on display.
>
> Image toolkit
> Choose which image toolkit to use if you have installed optional toolkits.
>
> **Settings**
> **Video Embed Field module settings**
>
> YouTube settings
> Configure sitewide settings for embedded YouTube video fields.

**Comment by laryn** [comment]
Thanks @olafgrabienski!
