### ISSUE TITLE
Warning: Undefined array key "title" in video_embed_field_handle_vimeo()

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/video_embed_field#26]
Seeing this in the log on a site, I believe because a video was set to private on Vimeo:

> Warning: Undefined array key "title" in video_embed_field_handle_vimeo() (line 539 of /app/modules/contrib/video_embed_field/video_embed_field.handlers.inc).

**Comment by herbdool** [comment]
@laryn simple change in PR, just checks for that particular array element.

**Comment by laryn** [comment]
Thanks @herbdool!
