### ISSUE TITLE
Automatic conversion of false to array is deprecated in video_embed_field_get_video_data()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/video_embed_field#27]
> Deprecated function: Automatic conversion of false to array is deprecated in video_embed_field_get_video_data() (line 492 of /app/httpdocs/modules/contrib/video_embed_field/video_embed_field.module).

If the handler can't fetch the data for a video, then `$data` is false and it shouldn't be assigned an array element.

There's a side issue that the admin settings form for setting the youtube api key doesn't seem to be available. But at any rate, the video still seems to load, so maybe fix `video_embed_field_get_video_data()` so that if `$data` is false, have it just return FALSE.

**Comment by herbdool** [comment]
@laryn got a PR.

**Comment by laryn** [comment]
Thanks @herbdool!
