### ISSUE TITLE
No menu item for admin/config/media/vef/settings

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/video_embed_field#28]
In `hook_menu`, `admin/config/media/vef/settings` is defined as `MENU_NORMAL_ITEM` but I don't see it appearing. Maybe Preset API interferes with this?

I think the easiest is to make the settings a different path. Perhaps just `admin/config/media/vef-settings`. That's similar to how images are done: the styles are a separate menu item.

**Comment by laryn** [comment]
@herbdool I made an alternate PR to try to clarify the menus. See what you think. If possible, I'd like to keep the VEF menu items all contained together to prevent menu sprawl.

![CleanShot 2024-03-26 at 13 52 21@2x](https://github.com/backdrop-contrib/video_embed_field/assets/871421/9aae8f88-ca2d-4fd5-ac64-a40e906b0644)

https://github.com/backdrop-contrib/video_embed_field/pull/32

**Comment by herbdool** [comment]
@laryn If `admin_bar` module isn't enabled, there's still no way to get to that settings page, except by typing in the path. All you see is:

![2024-03-26 15 16 39 bd3 lndo site f5998e8a04b7](https://github.com/backdrop-contrib/video_embed_field/assets/1071483/bc534447-3759-4dcf-9913-8a7b4319b853)

How about you also change the menu to `MENU_LOCAL_TASK`:

```
$items['admin/config/media/vef/settings'] = array(
    'title' => 'Settings',
    'description' => 'Video Embed Field settings',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('video_embed_field_settings_form'),
    'file' => 'video_embed_field.admin.inc',
    'access arguments' => array('administer video styles'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );
```
Then it appears as a tab:

![2024-03-26 15 29 05 bd3 lndo site 874870b9026e](https://github.com/backdrop-contrib/video_embed_field/assets/1071483/79844d2e-69d3-45c3-8913-9b30c0085a2f)

**Comment by laryn** [comment]
That works. 
![CleanShot 2024-03-26 at 14 36 55@2x](https://github.com/backdrop-contrib/video_embed_field/assets/871421/7739df38-bdfb-4468-a98b-8f0f9b3410b6)


And it's also linked from the module page:
![CleanShot 2024-03-26 at 14 37 23@2x](https://github.com/backdrop-contrib/video_embed_field/assets/871421/715bc1f5-0760-409e-b404-5f87306ebfdd)

**Comment by herbdool** [comment]
@laryn looks good
