### ISSUE TITLE
Undefined function entity_metadata_field_default_property_callback()

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/video_embed_field#7]
I ran into this on a dev site today:

> Error: Call to undefined function entity_metadata_field_default_property_callback() in video_embed_field_property_info_callback() (line 35 of /app/modules/video_embed_field/video_embed_field.field.inc).

This looks like  a function that is now in Entity Plus. I'll provide a PR for discussion -- it would mean adding a dependency on Entity Plus.

**Comment by laryn** [comment]
PR: https://github.com/backdrop-contrib/video_embed_field/pull/8

**Comment by serundeputy** [comment]
thanks! https://github.com/backdrop-contrib/video_embed_field/pull/8 merged.
