### ISSUE TITLE
Archive.org handler option

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/video_embed_field#9]
Hi! I have started to work on porting the Archive.org handler (I have not created a repository on github yet, but will pop it in here when I do) from Drupal 7. Once it is fully functional and tested, should I make a PR to have the handler included in this module, or would the preference be for the handler to remain in its own separate module?

**Comment by kelizoliva** [comment]
That ghost was me, I consolidated github accounts today. I have an initial port of the Archive.org handler which is working fine aside from thumbnail issues, for which I have created an issue in the repository about.

https://github.com/backdrop-contrib/video_embed_archive

**Comment by serundeputy** [comment]
Thanks @kelizoliva 

I don't have a strong preference so i'd defer to you on whatever you think is easiest, most convienient experience.

I've not been very active with this module so if you are interested in maintaining we can add you to the `README.md` and you can merge away so that I'm not blocking progress.

**Comment by kelizoliva** [comment]
@serundeputy sure, you can add me. :)

I feel like having archive.org as an out of the box option with this plugin would be ideal, given several non-profit orgs use archive.org fore media storage.

**Comment by laryn** [comment]
@kelizoliva I just got added as a maintainer and am browsing the issues. I see you are a maintainer-in-waiting -- still interested?

**Comment by kelizoliva** [comment]
hey @laryn - theoretically yes, however I will be totally underwater until next year so I would not be a very useful maintainer until then!

**Comment by laryn** [comment]
Closing for now due to lack of movement and the fact that this exists as a separate contrib repo.
